// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwdCNYv1hYTCk3oEOpVOffs6ScZbVoDo',
    appId: '1:684051928464:android:8fad05911cba33cc1a8f15',
    messagingSenderId: '684051928464',
    projectId: 'izichat-ff340',
    storageBucket: 'izichat-ff340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3pQ7AqFmgkxYiu_fGVdtIFjm8rUK7x0M',
    appId: '1:684051928464:ios:9221c7661168c4b51a8f15',
    messagingSenderId: '684051928464',
    projectId: 'izichat-ff340',
    storageBucket: 'izichat-ff340.appspot.com',
    androidClientId: '684051928464-ebt7ds3hobdg950ip0tj267l4bir2p9v.apps.googleusercontent.com',
    iosClientId: '684051928464-ire29g7f6dsp8fm4u0gi4poelvnogl2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.izipiziChat',
  );
}
